name: Action Test
description: Test
inputs:
  country:
    required: true
  environment:
    required: true

runs:
  using: composite
  steps:
    - name: Leyendo fichero
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/midnattsol/metadata/refs/heads/main/metadata/${{ inputs.country }}/${{ inputs.environment }}.yml | \
        sed 's/ /%20/g'); do
          decoded=$(echo "$line" | sed 's/%20/ /g')
          key=$(echo "$decoded" | cut -d':' -f1 | xargs)
          value=$(echo "$decoded" | cut -d':' -f2- | xargs)
          env_var=$(echo "$key" | tr '[:lower:]' '[:upper:]')
          echo "${env_var}=${value}" >> $GITHUB_ENV
        done