name: Action Test
description: Test
inputs:
  country:
    required: true
  environment:
    required: true

runs:
  using: composite
  steps:
    - name: Leyendo fichero
      shell: bash
      run: |
        METADATA=$(curl -SL https://raw.githubusercontent.com/midnattsol/metadata/refs/heads/main/metadata/${{ inputs.country }}/${{ inputs.environment }}.yml)
        echo "METADATA=$METADATA" >> $GITHUB_ENV