name: Action Test
description: Test
inputs:
  country:
    required: true
  environment:
    required: true

runs:
  using: composite
  steps:
    - name: Leyendo fichero
      shell: bash
      run: |
        # Descargar el archivo YAML
        yaml_content=$(curl -sSL "https://raw.githubusercontent.com/midnattsol/metadata/main/metadata/${{ inputs.country }}/${{ inputs.environment }}.yml")
        
        # Procesar cada línea del YAML
        while IFS= read -r line; do
          # Saltar líneas vacías o comentarios
          [[ -z "$line" || "$line" =~ ^# ]] && continue
          
          # Extraer clave y valor
          key=$(echo "$line" | awk -F':' '{print $1}' | xargs)
          value=$(echo "$line" | awk -F':' '{sub(/[^:]+:/, ""); print}' | xargs)
          
          # Convertir clave a mayúsculas para nombre de variable de entorno
          env_var=$(echo "$key" | tr '[:lower:]' '[:upper:]')
          
          # Exportar variable de entorno
          echo "$env_var=$value" >> $GITHUB_ENV
          echo "Defined environment variable: $env_var"
        done <<< "$yaml_content"